chat/urls.py
from django.contrib import admin
from django.urls import path

from . import views

from django.contrib.auth import views as auth_views
app_name = 'chat'

urlpatterns = [
    path('start_chat/', views.private_chat_room_view, name="start_chat"),
    path('create_or_return_private_chat/', views.create_or_return_private_chat, name='create-or-return-private-chat'), # TODO: ADD THIS LINE.
    path('start_new_chat/<int:id>', views.start_new_chat, name="start_new_chat"),
]

collabstr/urls.py
import imp
import site
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from user.sitemaps import StaticViewSitemap

from user.sitemaps2 import PostSitemap


sitemaps2={
    'posts':PostSitemap
}

sitemaps = {
    'static': StaticViewSitemap,
    'posts':PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sitemap.xml',sitemap, {'sitemaps':sitemaps,}, name='django.contrib.sitemaps.views.sitemap'),
    path(
        'sitemap2.xml',sitemap, {'sitemaps':sitemaps2}, name='django.contrib.sitemaps.views.sitemap'
    ),
    path('accounts/', include('allauth.urls')),
    path('', include('user.urls')),
    path('', include('chat.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

chat/models.py
import imp
from pickle import TRUE
from django.db import models
from django.conf import settings
from user.models import Orders, JoinInfluencer, JoinBrand


class PrivateChatRoom(models.Model):
	"""
	A private room for people to chat in.
	"""
	brand               = models.ForeignKey(JoinBrand, on_delete=models.CASCADE, related_name="brand", null=TRUE)
	influencer          = models.ForeignKey(JoinInfluencer, on_delete=models.CASCADE, related_name="influencer", null=True)

	is_active 			= models.BooleanField(default=False)

	@property
	def group_name(self):
		"""
		Returns the Channels Group name that sockets should subscribe to to get sent
		messages as they are generated.
		"""
		return f"PrivateChatRoom-{self.id}"


class RoomChatMessageManager(models.Manager):
	def by_room(self, room):
		qs = RoomChatMessage.objects.filter(room=room).order_by("-timestamp")
		return qs

class RoomChatMessage(models.Model):
	"""
	Chat message created by a user inside a Room
	"""
	user                = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	room                = models.ForeignKey(PrivateChatRoom, on_delete=models.CASCADE)
	timestamp           = models.DateTimeField(auto_now_add=True)
	content             = models.TextField(unique=False, blank=False,)

	objects = RoomChatMessageManager()

	def __str__(self):
		return self.content

chat/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from user.models import JoinInfluencer, JoinInfluencer
from chat.models import PrivateChatRoom, RoomChatMessage
import json
from django.http import HttpResponse
from user.models import *
from .utils import find_or_create_private_chat
from django.contrib.auth import get_user_model
from django.core import serializers
from datetime import timedelta
from django.db.models.functions import Now
import stripe
User = get_user_model()


DEBUG = False

def private_chat_room_view(request, *args, **kwargs):
	user = request.user

	# Redirect them if not authenticated
	if not user.is_authenticated:
		return redirect("login")

	if request.user.is_brand:
		brand_obj = JoinBrand.objects.get(user=request.user)
		chat_room = PrivateChatRoom.objects.filter(brand=brand_obj)

		if chat_room:

			context = {
				'debug':DEBUG,
				'debug_mode':settings.DEBUG,
				'chat_room':chat_room,
				'chat_room_display':chat_room[0],
				'friend_id': chat_room[0].influencer.user.id
			}
		else:
			context = {
				'debug':DEBUG,
				'debug_mode':settings.DEBUG,
				'chat_room':chat_room,
				'chat_room_display':''
			}
		return render(request, 'chat/order.html',context)
	else:
		influencer_obj = JoinInfluencer.objects.get(user=request.user)
		chat_room = PrivateChatRoom.objects.filter(influencer=influencer_obj)

		if chat_room:

			context = {
				'debug':DEBUG,
				'debug_mode':settings.DEBUG,
				'chat_room':chat_room,
				'chat_room_display':chat_room[0],
				'friend_id': chat_room[0].brand.user.id
			}
		else:
			context = {
				'debug':DEBUG,
				'debug_mode':settings.DEBUG,
				'chat_room':chat_room,
				'chat_room_display':''
			}
		return render(request, 'chat/order.html',context)

def get_order_list(orders_obj):

	order_list = []

	for order in orders_obj:
		temp = {
			'influencer_name':order.influencer.full_name,
			'brand_name':order.brand.full_name,
			'date':str(order.timestamp.date()),
			'price':order.price,
			'status':order.status
		}
		order_list.append(temp)

	return order_list

# Ajax call to return a private chatroom or create one if does not exist
def create_or_return_private_chat(request, *args, **kwargs):
	user1 = request.user
	payload = {}
	if user1.is_authenticated:
		if request.method == "POST":
			user2_id = request.POST.get("user2_id")
			try:
				user2 = User.objects.get(id=user2_id)
				if request.user.is_brand:
					brand_obj = JoinBrand.objects.get(user=user1)
					influencer_obj = JoinInfluencer.objects.get(user=user2)
					chat = PrivateChatRoom.objects.get(brand=brand_obj, influencer=influencer_obj)

					temp_orders = Orders.objects.filter(timestamp__lte=Now()-timedelta(days=3))

					for odr in temp_orders:
						odr.delete()

					orders_obj = Orders.objects.filter(influencer=influencer_obj, brand=brand_obj, status="pending")
					panding_orders = get_order_list(orders_obj)

					orders_obj = Orders.objects.filter(influencer=influencer_obj, brand=brand_obj, status="accept")
					accept_orders = get_order_list(orders_obj)

					orders_obj = Orders.objects.filter(influencer=influencer_obj, brand=brand_obj, status="complete")
					complete_orders = get_order_list(orders_obj)

					payload['response'] = "Successfully got the chat."
					payload['chatroom_id'] = chat.id
					payload['panding_orders'] = panding_orders
					payload['accept_orders'] = accept_orders
					payload['complete_orders'] = complete_orders
				else:
					brand_obj = JoinBrand.objects.get(user=user2)
					influencer_obj = JoinInfluencer.objects.get(user=user1)
					chat = PrivateChatRoom.objects.get(brand=brand_obj, influencer=influencer_obj)
					
					orders_obj = Orders.objects.filter(influencer=influencer_obj, brand=brand_obj, status="pending")
					panding_orders = get_order_list(orders_obj)

					orders_obj = Orders.objects.filter(influencer=influencer_obj, brand=brand_obj, status="accept")
					accept_orders = get_order_list(orders_obj)

					orders_obj = Orders.objects.filter(influencer=influencer_obj, brand=brand_obj, status="complete")
					complete_orders = get_order_list(orders_obj)

					payload['response'] = "Successfully got the chat."
					payload['chatroom_id'] = chat.id
					payload['panding_orders'] = panding_orders
					payload['accept_orders'] = accept_orders
					payload['complete_orders'] = complete_orders
			except User.DoesNotExist:
				payload['response'] = "Unable to start a chat with that user."
	else:
		payload['response'] = "You can't start a chat if you are not authenticated."
	return HttpResponse(json.dumps(payload), content_type="application/json")

def start_new_chat(request,id):
	brand_obj = JoinBrand.objects.get(user=request.user)
	chat_room = PrivateChatRoom.objects.filter(brand=brand_obj)
	influencer_obj = JoinInfluencer.objects.get(id=id)

	if chat_room:

		context = {
			'debug':DEBUG,
			'debug_mode':settings.DEBUG,
			'chat_room':chat_room,
			'chat_room_display':chat_room[0],
			'friend_id': influencer_obj.user.id
		}
	else:
		context = {
			'debug':DEBUG,
			'debug_mode':settings.DEBUG,
			'chat_room':chat_room,
			'chat_room_display':''
		}
	return render(request, 'chat/order.html',context)

chat/templates/chat/sockets.html
<script type="text/javascript">

	document.getElementById("site-footer").style.display = "none";

	var chatSocket = null;
	var roomId = null;

	onStart()

	function onStart() {
		{% if chat_room %}
			onSelectFriend2("{{friend_id}}")
		{% endif %}
		// {% for x in m_and_f %}
		// 	preloadImage("{{x.friend..url|safe}}", "id_friend_img_{{x.friend.id}}")
		// {% endfor %}
	}

	document.getElementById("back_to_chat_list").addEventListener("click", function () {
		document.getElementById("orders_list_are").style.display = "block";
		document.getElementById("chat_area").style.display = "none";
		document.getElementById("nav-div").style.display= "block";
	});

	function onSelectFriend(friendID) {
		if (window.innerWidth <= 684) {
			document.getElementById("orders_list_are").style.display = "none";
			document.getElementById("chat_area").style.display = "block";

			document.getElementById("nav-div").style.display= "none";
		}
		createOrReturnPrivateChat(friendID)
	}

	function onSelectFriend2(friendID) {
		createOrReturnPrivateChat(friendID)
	}

	function closeWebSocket() {
		if (chatSocket != null) {
			chatSocket.close()
			chatSocket = null
			clearChatLog()
			setPageNumber("1")
		}
	}

	function setupWebSocket(room_id) {

		console.log("setupWebSocket: " + room_id)

		roomId = room_id

		// close previous socket if one is open
		closeWebSocket()

		// Correctly decide between ws:// and wss://
		var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
		{% if debug_mode %}
		var ws_path = ws_scheme + '://' + window.location.host + "/chat/" + roomId + "/"; // development
		{% else %}
		var ws_path = ws_scheme + '://' + window.location.host + ":8000/chat/" + roomId + "/"; // production
		{% endif %}


		// console.log("Connecting to " + ws_path);
		chatSocket = new WebSocket(ws_path);

		// Handle incoming messages
		chatSocket.onmessage = function (message) {
			// Decode the JSON
			// console.log("Got chat websocket message " + message.data);
			console.log("Got websocket message.");
			var data = JSON.parse(message.data);

			// display the progress bar?
			//displayChatroomLoadingSpinner(data.display_progress_bar)

			// Handle errors (ClientError)
			if (data.error) {
				console.error(data.error + ": " + data.message)
				showClientErrorModal(data.message)
				return;
			}
			// Handle joining (Client perspective)
			if (data.join) {
				console.log("Joining room " + data.join);
				getUserInfo()
				getRoomChatMessages()
				enableChatLogScrollListener()
			}
			// Handle leaving (client perspective)
			if (data.leave) {
				// do nothing
				console.log("Leaving room " + data.leave);
			}

			// user info coming in from backend
			if (data.user_info) {
				handleUserInfoPayload(data.user_info)
			}

			// Handle getting a message
			if (data.msg_type == 0 || data.msg_type == 1 || data.msg_type == 2) {
				appendChatMessage(data, false, true)
			}

			// new payload of messages coming in from backend
			if (data.messages_payload) {
				handleMessagesPayload(data.messages, data.new_page_number)
			}
		};

		chatSocket.addEventListener("open", function (e) {
			console.log("ChatSocket OPEN")
			// join chat room
			if ("{{request.user.is_authenticated}}") {
				chatSocket.send(JSON.stringify({
					"command": "join",
					"room": roomId
				}));
			}
		})

		chatSocket.onclose = function (e) {
			console.log('Chat socket closed.');
		};

		chatSocket.onOpen = function (e) {
			console.log("ChatSocket onOpen", e)
		}

		chatSocket.onerror = function (e) {
			console.log('ChatSocket error', e)
		}

		if (chatSocket.readyState == WebSocket.OPEN) {
			console.log("ChatSocket OPEN")
		} else if (chatSocket.readyState == WebSocket.CONNECTING) {
			console.log("ChatSocket connecting..")
		}
	}

	document.getElementById('id_chat_message_input').focus();



	function focusFunction() {
		if (window.innerWidth <= 684) {
			for (let i = 0; i < document.querySelectorAll(".mobile-nav-holder").length; i++) {
				document.querySelectorAll(".mobile-nav-holder")[i].style.display = "none";

				document.getElementById("id_chat_log").style.height = "78vh";

				// document.getElementById("container").style.height = "80vh";
			}
		}
	}

	function focusOutFunction() {
		if (window.innerWidth <= 684) {
			for (let i = 0; i < document.querySelectorAll(".mobile-nav-holder").length; i++) {
				document.querySelectorAll(".mobile-nav-holder")[i].style.display = "flex";

				document.getElementById("id_chat_log").style.height = "69vh";
			}
		}
	}

	function keyPressFunction(e){

		if (document.getElementById('id_chat_message_input').value == "") {
			document.getElementById("send-img").style.display = "flex";
			document.getElementById("send-btn").style.display = "none";
		} else {
			document.getElementById("send-btn").style.display = "block";
			document.getElementById("send-img").style.display = "none";
		}

		if (e.keyCode === 13 && e.shiftKey) {  // enter + return
			// Handled automatically by textarea
		}
		else if (e.keyCode === 13 && !e.shiftKey) { // enter + !return
			const messageInputDom = document.getElementById('id_chat_message_input');
			const message = messageInputDom.value;
			chatSocket.send(JSON.stringify({
				"command": "send",
				"message": message,
				"room": roomId
			}));
			messageInputDom.value = '';
		}
	};

	document.getElementById("send-btn").addEventListener("click", function () {

		console.log("click *********");
		const messageInputDom = document.getElementById('id_chat_message_input');
		const message = messageInputDom.value;
		chatSocket.send(JSON.stringify({
			"command": "send",
			"message": message,
			"room": roomId
		}));
		messageInputDom.value = '';

		document.getElementById("send-img").style.display = "flex";
		document.getElementById("send-btn").style.display = "none";

	});

	// document.getElementById('id_chat_message_submit').onclick = function(e) {
	// const messageInputDom = document.getElementById('id_chat_message_input');
	// const message = messageInputDom.value;
	// chatSocket.send(JSON.stringify({
	// 	"command": "send",
	// 	"message": message,
	// 	"room": roomId
	// }));
	// messageInputDom.value = '';
	// };

	/*
	Retrieve the user information of the user other in the chat.
	2. username
	3. etc...
	*/
	function getUserInfo() {
		chatSocket.send(JSON.stringify({
			"command": "get_user_info",
			"room_id": roomId,
		}));
	}

	function handleUserInfoPayload(user_info) {
		document.getElementById("id_other_username").innerHTML = user_info['username']
	}

	function showClientErrorModal(message) {
		document.getElementById("id_client_error_modal_body").innerHTML = message
		document.getElementById("id_trigger_client_error_modal").click()
	}

	function appendChatMessage(data, maintainPosition, isNewMessage) {
		messageType = data['msg_type']
		msg_id = data['msg_id']
		message = data['message']
		uName = data['username']
		user_id = data['user_id']
		console.log("append chat message: " + messageType)

		var msg = "";
		var username = ""

		// determine what type of msg it is
		switch (messageType) {
			case 0:
				// new chatroom msg
				username = uName + ": "
				msg = message + '\n'
				createChatMessageElement(msg, msg_id, username, user_id, maintainPosition, isNewMessage)
				break;
			case 1:
				// User joined room
				createConnectedDisconnectedElement(message, msg_id, user_id)
				break;
			case 2:
				// User left room
				createConnectedDisconnectedElement(message, msg_id, user_id)
				break;
			default:
				console.log("Unsupported message type!");
				return;
		}
	}

	/*
	Build a new ChatMessage element and append to the list
	*/
	function createChatMessageElement(msg, msg_id, username, user_id, maintainPosition, isNewMessage) {
		var chatLog = document.getElementById("id_chat_log")

		var newMessageDiv = document.createElement("div")
		newMessageDiv.classList.add("message-container")
		if (String(username) == String("{{request.user.username}}" + ": ")) {
			newMessageDiv.classList.add("message-by-user")
		}


		var div1 = document.createElement("div")
		div1.classList.add("d-flex")
		div1.classList.add("flex-column")
		if (String(username) == String("{{request.user.username}}" + ": ")) {
			div1.classList.add("message-inner-div")
		} else {
			div1.classList.add("message-inner-div-2")
		}



		var msgP = document.createElement("p")
		msgP.innerHTML = msg
		msgP.classList.add("msg-p")
		div1.appendChild(msgP)

		newMessageDiv.appendChild(div1)

		if (isNewMessage) {
			chatLog.insertBefore(newMessageDiv, chatLog.firstChild)
		}
		else {
			chatLog.appendChild(newMessageDiv)
		}

		if (!maintainPosition) {
			chatLog.scrollTop = chatLog.scrollHeight
		}

		chatLog.scrollHeight;

	}

	function createConnectedDisconnectedElement(msg, msd_id, user_id) {
		// var chatLog = document.getElementById("connection-status")

		// if(user_id != "{{request.user.id}}"){
		// 	let temp = msg.split(" ");
		// 	chatLog.innerHTML = temp[1]
		// }

	}

	function setPageNumber(pageNumber) {
		document.getElementById("id_page_number").innerHTML = pageNumber
	}

	function clearChatLog() {
		document.getElementById("id_chat_log").innerHTML = ""
	}


	function setPaginationExhausted() {
		setPageNumber("-1")
	}

	/*
	  Retrieve the chat room messages given the page number.
  */
	function getRoomChatMessages() {
		var pageNumber = document.getElementById("id_page_number").innerHTML
		if (pageNumber != "-1") {
			setPageNumber("-1") // loading in progress
			chatSocket.send(JSON.stringify({
				"command": "get_room_chat_messages",
				"room_id": roomId,
				"page_number": pageNumber,
			}));
		}
	}


	function handleMessagesPayload(messages, new_page_number) {
		if (messages != null && messages != "undefined" && messages != "None") {
			setPageNumber(new_page_number)
			messages.forEach(function (message) {
				appendChatMessage(message, true, false)
			})
		}
		else {
			setPaginationExhausted() // no more messages
		}
	}


	/*
			Get the next page of chat messages when scrolls to bottom
		*/
	function chatLogScrollListener(e) {
		var chatLog = document.getElementById("id_chat_log")
		if ((Math.abs(chatLog.scrollTop) + 2) >= (chatLog.scrollHeight - chatLog.offsetHeight)) {
			getRoomChatMessages()
		}
	}

	/*
		Enable the function "chatLogScrollListener"
	*/
	function enableChatLogScrollListener() {
		document.getElementById("id_chat_log").addEventListener("scroll", chatLogScrollListener);
	}

	/*
		Disable the function "chatLogScrollListener"
	*/
	function disableChatLogScrollListener() {
		document.getElementById("id_chat_log").removeEventListener("scroll", chatLogScrollListener)
	}


	function createOrReturnPrivateChat(friendID) {
		payload = {
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"user2_id": friendID,
		}
		$.ajax({
			type: 'POST',
			dataType: "json",
			url: "{% url 'chat:create-or-return-private-chat' %}", // production
			data: payload,
			timeout: 5000,
			success: function (data) {
				console.log("SUCCESS", data)
				if (data['response'] == "Successfully got the chat.") {

					setupWebSocket(data['chatroom_id'])
					
					console.log("********************");
					console.log(data['panding_orders'],"******************");
					
					const panding_order_body = document.getElementById("panding_order_body");
					const accept_order_body = document.getElementById("accept_order_body");
					const complete_order_body = document.getElementById("complete_order_body");
					
					let pop_up_data = "";
					for(let i=0; i<data['panding_orders'].length; i++){
						pop_up_data += '<tr>{% if request.user.is_brand %}<td><b>'+data['panding_orders'][i]['influencer_name']+'</b></td>{% else %}<td style="color: #a0a0a0;">'+data['panding_orders'][i]['brand_name']+'</td>{% endif %}<td>'+data['panding_orders'][i]['date']+'</td><td><b>'+data['panding_orders'][i]['price']+'</b></td><td><samp class="pending-status">'+data['panding_orders'][i]['status']+'</samp></td></tr>';
					}
					panding_order_body.innerHTML = pop_up_data;

					pop_up_data = "";
					for(let i=0; i<data['accept_orders'].length; i++){
						pop_up_data += '<tr>{% if request.user.is_brand %}<td><b>'+data['accept_orders'][i]['influencer_name']+'</b></td>{% else %}<td style="color: #a0a0a0;">'+data['accept_orders'][i]['brand_name']+'</td>{% endif %}<td>'+data['accept_orders'][i]['date']+'</td><td><b>'+data['accept_orders'][i]['price']+'</b></td><td><samp class="pending-status">'+data['accept_orders'][i]['status']+'</samp></td></tr>';
					}
					accept_order_body.innerHTML = pop_up_data;

					pop_up_data = "";
					for(let i=0; i<data['complete_orders'].length; i++){
						pop_up_data += '<tr>{% if request.user.is_brand %}<td><b>'+data['complete_orders'][i]['influencer_name']+'</b></td>{% else %}<td style="color: #a0a0a0;">'+data['complete_orders'][i]['brand_name']+'</td>{% endif %}<td>'+data['complete_orders'][i]['date']+'</td><td><b>'+data['complete_orders'][i]['price']+'</b></td><td><samp class="pending-status">'+data['complete_orders'][i]['status']+'</samp></td></tr>';
					}
					complete_order_body.innerHTML = pop_up_data;

				}
				else if (data['response'] != null) {
					alert(data['response'])
				}
			},
			error: function (data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
		});
	}
</script>